name: Renewal

on:
  schedule:
    - cron: '0 8 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          repository: 'mkorthof/freenom-script'
      - name: Install freenom-script
        run: sudo make install
      - name: Configure freenom-script
        run: |
          cat << EOF > ./freenom.conf
          ${{ secrets.CONF }}
          EOF
      - name: random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-1800 -n 1)
      - name: run script
        run: freenom.sh -r -a -c ./freenom.conf &> /dev/null